//
//  AchievementsPresenter.swift
//  ProjectStash
//
//  Created Julio Reyes on 7/25/18.
//  Copyright © 2018 Julio Reyes. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AchievementsPresenter: AchievementsPresenterProtocol {
    var investor: InvestorModel?
    
    var wireFrame: AchievementsWireframeProtocol?
    
    weak internal var view: AchievementsViewProtocol?
    var interactor: AchievementsInteractorProtocol?
    var router: AchievementsWireframeProtocol?
    
    init(interface: AchievementsViewProtocol, interactor: AchievementsInteractorProtocol?, router: AchievementsWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func viewDidLoad(){
        interactor?.retrieveInvestorList()
    }

}

extension AchievementsPresenter{    
    func didRetrieveAchievements(_ investor: [InvestorModel]) {
        view?.showAchievements(forInvestor: investor)
    }
}
